[project]
name = "dcelery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "celery>=5.5.3",
    "django>=4.2.24",
    "redis>=6.4.0",
]
